### ISSUE TITLE
update pkgdown.yml template

### ISSUE THREAD

**Issue by ernestguevarra** [katilingban/ppitables#102]
```yaml
template:
  bootstrap: 5
  bootswatch: sandstone
  theme: breeze-light
```
